services:
  # Nginx Service (Reverse Proxy)
  nginx:
    image: inception-nginx
    container_name: inception-nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "8081:8081"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ../html:/var/www/static:ro
    networks:
      - inception_network
    depends_on:
      wordpress:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env

  # WordPress Service
  wordpress:
    image: inception-wordpress
    container_name: inception-wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  # MariaDB Service
  mariadb:
    image: inception-mariadb
    container_name: inception-mariadb
    build: ./requirements/mariadb
    env_file: .env
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      # Use the root user for the healthcheck, as the wordpress user may not exist yet.
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis Service
  redis:
    image: inception-redis
    container_name: inception-redis
    build: ./requirements/redis
    env_file: .env
    networks:
      - inception_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  # Adminer Service
  adminer:
    container_name: inception-adminer
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - inception_network
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy

  # FTP Service
  ftp:
    image: inception-ftp
    container_name: inception-ftp
    build:
      context: ./requirements/ftp
      dockerfile: Dockerfile
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    ports:
      - "20:20"
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      wordpress:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env

networks:
  inception_network:
    driver: bridge
    name: inception_network

volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local
