# This file overrides the volume definitions in the main docker-compose.yml
# to use host-bind mounts as required by the 42 subject.
# Use 'make up-host' or any command with 'MODE=host' (e.g., 'make logs MODE=host') to run with these settings.

services:
  nginx:
    volumes:
      - /home/${LOGIN}/data/wordpress:/var/www/html:ro

  wordpress:
    volumes:
      - /home/${LOGIN}/data/wordpress:/var/www/html

  mariadb:
    volumes:
      - /home/${LOGIN}/data/mariadb:/var/lib/mysql
