services:
  # Nginx Service (Reverse Proxy)
  nginx:
    container_name: nginx
    image: nginx # Image name must be the same as the service name
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      # Use the named volume from the wordpress service.
      # This ensures Nginx can read the files WordPress creates.
      - wordpress_data:/var/www/html:ro
    networks:
      - inception_network
    depends_on:
      wordpress:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "service", "nginx", "status", "||", "exit", "1"]
      interval: 15s
      timeout: 5s
      retries: 3
    env_file:
      - .env

  # WordPress Service
  wordpress:
    container_name: wordpress
    image: wordpress # Image name must be the same as the service name
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      # Use a Docker-managed named volume for WordPress data.
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm7.4"]
      interval: 15s
      timeout: 5s
      retries: 3

  # MariaDB Service
  mariadb:
    container_name: mariadb
    image: mariadb # Image name must be the same as the service name
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      # Use a Docker-managed named volume for MariaDB data.
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 15s
      timeout: 5s
      retries: 3
    env_file:
      - .env

networks:
  inception_network:
    driver: bridge
    name: inception_network # Explicitly naming the network

# Define the Docker-managed volumes
volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local
