services:
  # Nginx Service (Reverse Proxy)
  nginx:
    container_name: nginx
    image: nginx # Image name must be the same as the service name
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      # Bind mount for WordPress files, allowing Nginx to access them directly.
      # The path uses the LOGIN variable passed from the Makefile.
      - /home/${LOGIN}/data/wordpress:/var/www/html:ro
    networks:
      - inception_network
    depends_on:
      wordpress:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "service", "nginx", "status", "||", "exit", "1"]
      interval: 15s
      timeout: 5s
      retries: 3
    env_file:
      - .env

  # WordPress Service
  wordpress:
    container_name: wordpress
    image: wordpress # Image name must be the same as the service name
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      # Bind mount for WordPress files.
      - /home/${LOGIN}/data/wordpress:/var/www/html
    networks:
      - inception_network
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm7.4"]
      interval: 15s
      timeout: 5s
      retries: 3

  # MariaDB Service
  mariadb:
    container_name: mariadb
    image: mariadb # Image name must be the same as the service name
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      # Bind mount for MariaDB data.
      - /home/${LOGIN}/data/mariadb:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped
    healthcheck:
      # Use the root user and password to perform the healthcheck ping.
      # This prevents the 'Access denied' warnings in the logs.
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 15s
      timeout: 5s
      retries: 3
    env_file:
      - .env

networks:
  inception_network:
    driver: bridge
    name: inception_network # Explicitly naming the network
